version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - bff
    networks:
      - app-network

  bff:
    build: ./bff
    ports:
      - "3001:3001"
      - "3002:3002"
    depends_on:
      - mq
      - api_storage
    networks:
      - app-network

  mq:
    build: ./mq
    ports:
      - "8081:8081"
    networks:
      - app-network

  api_storage:
    build: ./api_storage
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
